export const ROUTE_CHANGE = 'ROUTE_CHANGE';
export const NEW_LOCAL_SOURCE = 'NEW_LOCAL_SOURCE';
export const REMOVE_SOURCE = 'REMOVE_SOURCE';
export const LOAD_FROM_STORAGE = 'LOAD_FROM_STORAGE';
export const SCREEN_RESIZE = 'SCREEN_RESIZE';
